default_language_version:
    python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      args: [--config=pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      args: [--settings-path=pyproject.toml]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.10
  hooks:
    - id: ruff
      args: [--config=pyproject.toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
        - types-beautifulsoup4
        - pandas-stubs
      args: [--config-file=pyproject.toml]
