name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment and install dependencies
      run: |
        uv venv --python ${{ steps.setup_python.outputs.python-path }}
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Run black
      run: |
        source .venv/bin/activate
        black --check --config pyproject.toml src tests

    - name: Run isort and show diff
      run: |
        source .venv/bin/activate
        echo "RUNNING ISORT WITH --CHECK-ONLY on src/dwd_weather_pipeline/main.py:"
        isort --check-only --diff --settings-path pyproject.toml src/dwd_weather_pipeline/main.py
        echo "RUNNING ISORT WITH --CHECK-ONLY on src and tests (original broader check):"
        isort --check-only --settings-path pyproject.toml src tests

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy --config-file pyproject.toml src

    - name: Run ruff
      run: |
        source .venv/bin/activate
        ruff check --config pyproject.toml src tests

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --cov=src --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
